name: keep-repo-active

on:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

jobs:
  update-readme:
    if: github.repository == 'HarmonyCandies/.github-workflow'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Update keep-repo-active.txt
        run: |
          now=$(date +"%Y-%m-%d %H:%M:%S")
          echo -e "[临时文件] 用于保持仓库的活跃，避免 Github Action 被禁用，如果以后不再使用，请与 .github/workflows/keep-repo-active.yml 一并删除。 \n$now" > temp/keep-repo-active.txt
          cat temp/keep-repo-active.txt
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Update keep-repo-active.txt