name: "Update HarmonyCandies profile/README.md"

on:
  schedule:
    # Runs every 8 hours
    - cron: "0 0/8 * * *"
  workflow_dispatch:

# Disable permissions for all of the available permissions
permissions: {}

jobs:
  pub_dashboard_job:
    if: github.repository == 'HarmonyCandies/.github-workflow'
    runs-on: ubuntu-latest
    name: "pub-dashboard :: HarmonyCandies .github/profile/README.md"
    steps:
      - name: run pub-dashboard
        uses: AmosHuKe/pub-dashboard@b6e3ec7d3aa2c878582057672bd66762a06377ee
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: "https://github.com/HarmonyCandies/.github"
          filename: "profile/README.md"
          publisher_list: "harmonycandies.com"
          package_list: ""
          sort_field: "published"
          sort_mode: "asc"
          commit_message: "Update profile/README.md (CI - pub_dashboard_job)"
  ohpm_dashboard_job:
    if: github.repository == 'HarmonyCandies/.github-workflow'
    needs: pub_dashboard_job
    runs-on: ubuntu-latest
    name: "ohpm-dashboard :: HarmonyCandies .github/profile/README.md"
    steps:
      - name: run ohpm-dashboard
        uses: AmosHuKe/ohpm-dashboard@f74d925b8eff2b0c41d4f43daed2a0dc72c3067f
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: "https://github.com/HarmonyCandies/.github"
          filename: "profile/README.md"
          publisher_list: "6542179b6dad4e55f6635764"
          package_list: ""
          sort_field: "publishTime"
          sort_mode: "asc"
          commit_message: "Update profile/README.md (CI - ohpm_dashboard_job)"